### ISSUE TITLE
Latest releases are assuming raven.js is inlined

### ISSUE THREAD

**Issue by devinus** [damiencaselli/ember-cli-sentry#39]
You can no longer use the `cdn` option.

```
Build failed.
ENOENT: no such file or directory, stat '/Users/devinus/Projects/rebelmail-dashboard/tmp/source_map_concat-input_base_path-ZMpdzNJt.tmp/0/bower_components/raven-js/dist/raven.js'
Error: ENOENT: no such file or directory, stat '/Users/devinus/Projects/rebelmail-dashboard/tmp/source_map_concat-input_base_path-ZMpdzNJt.tmp/0/bower_components/raven-js/dist/raven.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/Users/devinus/Projects/rebelmail-dashboard/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/devinus/Projects/rebelmail-dashboard/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/devinus/Projects/rebelmail-dashboard/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickDomainCallback (node.js:426:13)
npm ERR! Test failed.  See above for more details.
```

**Comment by damiencaselli** [comment]
@devinus can you try using the `2.2.0-beta.` version?

It will require you to remove the introduced bower dependency, `bower uninstall --save raven-js`.

**Comment by mapohjola** [comment]
Upgrading to `2.2.0-beta.1` seems to fix this issue.

**Comment by damiencaselli** [comment]
Thanks for the feedback @mapohjola.
What was the setup you tested the upgrade against?

**Comment by mapohjola** [comment]
```
Ember Inspector 1.9.5
Ember 2.3.0
Ember Data 2.3.3
jQuery 1.11.3
```

**Comment by damiencaselli** [comment]
:+1:

**Comment by damiencaselli** [comment]
2.2.0 addresses this issue.
