### ISSUE TITLE
It doesn't seem to log exceptions from fastboot

### ISSUE THREAD

**Issue by kitsunde** [damiencaselli/ember-cli-sentry#59]
It doesn't seem to work with fastboot?

```js
2016-10-02T04:24:27.118Z 200 OK /website/our-work
Error: Raven has already been configured
Error while processing route: website.our-work.index Adapter operation failed Error: Adapter operation failed
    at new Error (native)
    at Error.t (/home/deploy/mediapop/staging/src/frontend/dist/fastboot/vendor-3ad452d7e54e7df8917456b27bab3c58.js:8:31720)
    at Error.i (/home/deploy/mediapop/staging/src/frontend/dist/fastboot/vendor-3ad452d7e54e7df8917456b27bab3c58.js:22:26)
    at r.handleResponse (/home/deploy/mediapop/staging/src/frontend/dist/fastboot/vendor-3ad452d7e54e7df8917456b27bab3c58.js:23:2850)
    at l (/home/deploy/mediapop/staging/src/frontend/dist/fastboot/vendor-3ad452d7e54e7df8917456b27bab3c58.js:22:3444)
    at Object.c.error (/home/deploy/mediapop/staging/src/frontend/dist/fastboot/vendor-3ad452d7e54e7df8917456b27bab3c58.js:22:6859)
    at fire (/home/deploy/mediapop/staging/src/frontend/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/home/deploy/mediapop/staging/src/frontend/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as reject] (/home/deploy/mediapop/staging/src/frontend/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at onError (/home/deploy/mediapop/staging/src/frontend/node_modules/najax/lib/najax.js:206:9)
    at dataHandler (/home/deploy/mediapop/staging/src/frontend/node_modules/najax/lib/najax.js:141:18)
    at IncomingMessage.<anonymous> (/home/deploy/mediapop/staging/src/frontend/node_modules/najax/lib/najax.js:194:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by damiencaselli** [comment]
Hi @kitsunde, unfortunately I haven't used or tested it with Fastboot yet.

From the `Error: Raven has already been configured` line in your logs, it seems you are trying to set Raven twice. Can you tell more about the setup you are using?

**Comment by kitsunde** [comment]
The exception above is unrelated, I've fixed it but I'm getting raven saying it's already configured multiple times through each request instead. I have `services/raven.js` that looks like this:

```js
import RavenLogger from 'ember-cli-sentry/services/raven';

export default RavenLogger.extend({

  unhandledPromiseErrorMessage: '',

  captureException(/* error */) {
    this._super(...arguments);
  },

  captureMessage(/* message */) {
    return this._super(...arguments);
  },

  enableGlobalErrorCatching() {
    return this._super(...arguments);
  },

  ignoreError() {
    return this._super();
  },

  callRaven(/* methodName, ...optional */) {
    return this._super(...arguments);
  }
});
```

**Comment by damiencaselli** [comment]
I'm not quite sure what can be the reason for this, but the only reason for getting the `Error: Raven has already been configured` message is your application getting initialized more than once (the code causing this message to appear is in an instance initializer).
It probably has to do with the way Fastboot manages the instances.

**Comment by damiencaselli** [comment]
@kitsunde ok I've dug a bit about this issue, and Raven.js cannot be run inside a Fastboot context **as it is**, because it uses `XMLHTTPRequest as default transport (undefined in node).

Fortunately Raven [provides an option](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L543-L556) to override it.
To override it with this add-on, you'll have to set it doing `this.get('raven').callRaven('setTransport', yourCustomTransport);`

I couldn't find any documentation about it, but the transport function is [given parameters](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L1350-L1370). Following the [`_makeRequest` implementation](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L1373-L1415) may be a good idea if you want to roll your own.

```js
// Dummy example

import Ember from 'ember';

export default Ember.Route.extend({

  renderTemplate: function() {
    this.get('raven').callRaven('setTransport', function(args) {
      const { url, auth } = args;
      delete args.url;
      delete args.auth;
      someXHRMethod(url + '?' + urlencode(auth), args);
    });
    this.get('raven').captureMessage(`"hello" captured from a route`);
    this._super(...arguments);
  }
});

```

This issue depends on Fastboot and Raven.js, and I don't plan on implementing a `_makeRequest`-like for node.
If someone wants to implement it, I'd gladly add it to the project.
