### ISSUE TITLE
Test loader failures in ember-cli 0.2.1

### ISSUE THREAD

**Issue by JoshSmith** [damiencaselli/ember-cli-sentry#7]
I'm not sure if this is related to `ember-cli-sentry` or not, but I'm seeing test loader failures after upgrading to `ember-cli 0.2.1`.

```
Died on test #1     at Object.TestLoader.moduleLoadFailure (http://localhost:4200/assets/test-support.js:5295:11)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:31:14)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:40:24)
    at http://localhost:4200/assets/test-support.js:5301:16
    at d (http://cdn.ravenjs.com/1.1.16/jquery,native/raven.min.js:2:12478): undefined is not a function
```

Should raven.js be loading in a testing environment? I'm not sure I see a reason for loading it.

**Comment by JoshSmith** [comment]
This may not be related. I set `ENV.sentry.skipCdn` to `true` in my testing environment block and that line no longer gets called, but the rest of the stack trace is there. Thinking this is unrelated and will likely close once I figure this out.

**Comment by JoshSmith** [comment]
Closing as unrelated.
